homepage:
    pattern:   /
    defaults:  { _controller: AppBundle:Contact:Index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app_contacts:
    resource: "@AppBundle/Resources/config/routing/contact.php"
    prefix:   /

